# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_organizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_path = QtWidgets.QLineEdit(self.frame)
        self.txt_path.setMinimumSize(QtCore.QSize(0, 28))
        self.txt_path.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_path.setObjectName("txt_path")
        self.horizontalLayout_2.addWidget(self.txt_path)
        self.btn_open = QtWidgets.QPushButton(self.frame)
        self.btn_open.setMinimumSize(QtCore.QSize(120, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_open.setFont(font)
        self.btn_open.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_open.setStyleSheet("QPushButton{border-top-right-radius:15px; background-color: rgb(234, 234, 234)}\n"
"QPushButton:hover{color:#fff; background-color: rgb(0, 157, 235)}")
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_2.addWidget(self.btn_open)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.btn_organize = QtWidgets.QPushButton(self.frame)
        self.btn_organize.setMinimumSize(QtCore.QSize(200, 31))
        self.btn_organize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_organize.setStyleSheet("QPushButton{background-color: rgb(234, 234, 234); border-radius: 15px}\n"
"QPushButton:hover{color:#fff; background-color: rgb(0, 157, 235)}")
        self.btn_organize.setObjectName("btn_organize")
        self.horizontalLayout.addWidget(self.btn_organize)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\"img/logo.png\"/></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#2f008d;\">FILE ORGANIZER</span></p></body></html>"))
        self.txt_path.setPlaceholderText(_translate("MainWindow", "Selecione a pasta"))
        self.btn_open.setText(_translate("MainWindow", "Open"))
        self.btn_organize.setText(_translate("MainWindow", "Organize"))
